#!/bin/bash
#-DELIVERY (APPS DEPLOYMENT)

CONTAINER=devops_pipeline_demo

RUNNING=$(sudo docker inspect --format="{{ .State.Running }}" $CONTAINER 2> /dev/null)
if [ $? -eq 1 ]; then
  echo "'$CONTAINER' does not exist."
else
  sudo docker rm -f $CONTAINER
fi

    # run your container
    echo ""
    echo "..... Deployment Phase Started :: Building Docker Container :: ....."
    sudo docker run -d -p 8180:8080 --name devops_pipeline_demo devops_pipeline_demo

#-Completion
echo "------------------------------------------------------"
echo "View App deployed here: http://jenkins:8180/sampel.txt"
echo "------------------------------------------------------"
